[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/console/*"
  to = "/ransa/:splat"
  status = 301

[[redirects]]
  from = "/ransa/*"
  to = "/ransa/index.html"
  status = 200
